vim.cmd("set number relativenumber")
vim.cmd("set autoindent")
vim.cmd("set expandtab")
vim.cmd("set tabstop=" .. Editor_indent_width_global)
vim.cmd("set softtabstop=" .. Editor_indent_width_global)
vim.cmd("set shiftwidth=" .. Editor_indent_width_global)
vim.cmd("set smarttab")
vim.cmd("set mouse=a")
vim.cmd("set scrolloff=7")
vim.cmd("set encoding=utf-8")
vim.cmd("set ignorecase")

vim.cmd("syntax enable")
